### PR TITLE
Streamline the github actions configuration

### PR DESCRIPTION
**Pull request by fire**
The installation of dependencies and setup for Windows has been removed

Instead of uploading all files from the install directory, only specific shared libraries are uploaded now.

### CODE REVIEW

**Comment by fire** [comment]
Todo: need to check that the artifacts are correctly uploaded

**Comment by fwsGonzo** [comment]
Was it not possible to use Clang-cl instead of cl? libriscv definitely builds and runs complex programs on Clang-cl. It's one of the things I test for each release.

It also builds in MinGW - which is how I build my game client.

**Comment by fire** [comment]
Does clang-cl ship with microsoft visual studio?

**Comment by fwsGonzo** [comment]
Yes, it's one of the install options. Same with git (which might be OK to have)

**Comment by fire** [comment]
There's three bugs here. One is windows support, the other is failing to upload and a can't compile bug.

So I want to focus on the upload shared library here.

```
# For the other pr.
    - name: Install Dependencies (Windows)
      if: matrix.config.os == 'windows-latest'
      run: |
        choco upgrade ccache ninja
  
    - name: Setup MSVC (Windows)
      if: matrix.config.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
```

**Pull request merged**
